if (process.env.APP_ENV === 'local') {
  process.env.APP_ENV = 'test'
  process.env.NODE_ENV = 'development'
  process.env.NODE_PORT = '8080'
  process.env.DB_URL = 'mongodb://mongo:27017'
  process.env.DB_DATABASE = 'test'
  process.env.DB_USERNAME = 'homestead'
  process.env.DB_PASSWORD = 'secret'
  process.env.DB_AUTH_SOURCE = 'admin'
  process.env.DB_SSL = 'false'
  process.env.DB_DELAY_RECONNECT_MS = '5000'
  process.env.DB_AUTO_INDEX = 'false'
  process.env.DB_RECONNECT_LIMIT = '5'
  process.env.URL_PREFIX = '/api/v1'
  process.env.K8S_TERMINATION_GRACE_PERIOD_MS = '30000'
}
