version: '3'
services:
    node:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        command: ['/bin/sh', '-c', 'yarn install --production=false && yarn dev']
        depends_on:
            - mongo
    mongo:
        image: registry.thinknet.co.th/sredev/mongo:5.0
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongo:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=homestead
            - MONGO_INITDB_ROOT_PASSWORD=secret
networks:
    default:
        external:
            name: microservicenetwork
