import Head from "next/head";
import React, { useState } from "react";
import Navbar from "../components/navbar";
import Footer from "../components/Footer";
import { AudioOutlined } from "@ant-design/icons";
import { Input, Space } from "antd";

const { Search } = Input;

const suffix = (
  <AudioOutlined
    style={{
      fontSize: 16,
      color: "#1890ff",
    }}
  />
);

function checkTicket(props) {
  const [ref_num, setRef_num] = useState("");

  const onSearch = () => {
    console.log(ref_num);
  };
  return (
    <>
      <Head>
        <title>S Major F: Check Ticket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <h1>Check For Ticket Information</h1>
      <Search
        placeholder="input search text"
        allowClear
        onSearch={onSearch}
        style={{ width: 200 }}
        onChange={(e) => setRef_num(e.target.value)}
      />
      <h2>Ticket detail here when data is here.</h2>

      <Footer />
    </>
  );
}

export default checkTicket;
