import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Footer from '../components/Footer'
import { Content } from 'antd/lib/layout/layout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>S Major F cineplex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Content>
        Welcome!
      </Content>

      <Footer />
    </div>
  )
}
