import Head from "next/head";
import React, {useState} from "react";
import { Button, Checkbox, Form, Input } from "antd";
import Navbar from "../components/navbar";
import Footer from "../components/Footer";

function login(props) {
    const [email,setEmail] = useState('')
    const [password, setPassword] = useState('')

    const onSubmit = () => {
        console.log(email)
        console.log(password)
    }

  return (
    <>
      <Head>
        <title>S Major F: Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>Login</h1>
      <Form
        name="basic"
        labelCol={{ span: 8 }}
        wrapperCol={{ span: 16 }}
        initialValues={{ remember: true }}
        onFinish={onSubmit}
        onFinishFailed={() => {
          console.log("submit fail");
        }}
        autoComplete="off"
      >
        <Form.Item
          label="Email"
          name="email"
          rules={[{ required: true, message: "Please input your email!" }]}
          style={{ width: "40%" }}
        >
          <Input type='email' onChange={e => setEmail(e.target.value)} />
        </Form.Item>

        <Form.Item
          label="Password"
          name="password"
          rules={[{ required: true, message: "Please input your password!" }]}
          style={{ width: "40%" }}
        >
          <Input.Password onChange={e => setPassword(e.target.value)}/>
        </Form.Item>
        {/* 
      <Form.Item name="remember" valuePropName="checked" wrapperCol={{ offset: 8, span: 16 }}>
        <Checkbox>Remember me</Checkbox>
      </Form.Item> */}

        <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
          <Button type="primary" htmlType="submit">
            Submit
          </Button>
        </Form.Item>
      </Form>

      <Footer />
    </>
  );
}

export default login;
