import Head from "next/head";
import React from 'react';
import Navbar from "../components/navbar";
import Footer from "../components/Footer";
import MoviesList from "../components/MoviesList";

function movieList(props) {
    return (
        <>
        <Head>
        <title>S Major F: Movies List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <Navbar />
                <MoviesList />
            <Footer />
        </>
    );
}

export default movieList;