import Head from "next/head";
import React, {useState} from "react";
import { Button, Checkbox, Form, Input } from "antd";
import Navbar from "../components/navbar";
import Footer from "../components/Footer";

function register(props) {
    const [email,setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [firstname,setFirstname] = useState('')
    const [lastname, setLastname] = useState('')

    const onSubmit = () => {
        console.log(firstname)
        console.log(lastname)
        console.log(email)
        console.log(password)
    }

  return (
    <>
    <Head>
        <title>S Major F: Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>Register</h1>
      <Form
        name="basic"
        labelCol={{ span: 8 }}
        wrapperCol={{ span: 16 }}
        initialValues={{ remember: true }}
        onFinish={() => {onSubmit}}
        onFinishFailed={() => {
          console.log("submit fail");
        }}
        autoComplete="off"
      >
        <Form.Item
          label="Firstname"
          name="firstname"
          rules={[{ required: true, message: "Please input your firstname!" }]}
          style={{ width: "40%" }}
        >
          <Input onChange={e => setFirstname(e.target.value)}/>
        </Form.Item>

        <Form.Item
          label="Lastname"
          name="lastname"
          rules={[{ required: true, message: "Please input your lastname!" }]}
          style={{ width: "40%" }}
        >
          <Input onChange={e => setLastname(e.target.value)}/>
        </Form.Item>
        <Form.Item
          label="Email"
          name="email"
          rules={[{ required: true, message: "Please input your email!" }]}
          style={{ width: "40%" }}
        >
          <Input type='email' onChange={e => setEmail(e.target.value)}/>
        </Form.Item>

        <Form.Item
          label="Password"
          name="password"
          rules={[{ required: true, message: "Please input your password!" }]}
          style={{ width: "40%" }}
        >
          <Input.Password onChange={e => setPassword(e.target.value)}/>
        </Form.Item>

        <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
          <Button type="primary" htmlType="submit" onClick={onSubmit}>
            Submit
          </Button>
        </Form.Item>
      </Form>

      <Footer />
    </>
  );
}

export default register;
