import Head from "next/head";
import React, {useState} from "react";
import { Button, Checkbox, Form, Input } from "antd";
import Navbar from "../components/navbar";
import Footer from "../components/Footer";
import { useMutation, useQuery, gql } from "@apollo/client";
import { useRouter } from 'next/router'

const doRegisterMutation = gql`
  mutation ($input: RegisterInput!) {
    register(input: $input) {
      success
    }
  }
`;

function register(props) {
    const [email,setEmail] = useState('')
    const [password, setPassword] = useState('')
    // const [confirmPassword, setConfirmPassword] = useState('')
    const [firstname,setFirstname] = useState('')
    const [lastname, setLastname] = useState('')

    const router = useRouter()
    
    const [register, { loading: mutationLoading, error: mutationError, data }] =
    useMutation(doRegisterMutation);

    const onSubmit = async () => {
        // console.log(firstname)
        // console.log(lastname)
        // console.log(email)
        // console.log(password)
        const RegisterInput = {
          email,
          password,
          firstname,
          lastname
        };
        await register({ variables: { input: RegisterInput } });

        router.push('/login')
    }

  return (
    <>
    <Head>
        <title>S Major F: Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <h1>Register</h1>
      <Form
        name="basic"
        labelCol={{ span: 8 }}
        wrapperCol={{ span: 16 }}
        initialValues={{ remember: true }}
        onFinish={() => {onSubmit}}
        onFinishFailed={() => {
          console.log("submit fail");
        }}
        autoComplete="off"
      >
        <Form.Item
          label="Firstname"
          name="firstname"
          rules={[{ required: true, message: "Please input your firstname!" }]}
          style={{ width: "40%" }}
        >
          <Input onChange={e => setFirstname(e.target.value)}/>
        </Form.Item>

        <Form.Item
          label="Lastname"
          name="lastname"
          rules={[{ required: true, message: "Please input your lastname!" }]}
          style={{ width: "40%" }}
        >
          <Input onChange={e => setLastname(e.target.value)}/>
        </Form.Item>
        <Form.Item
          label="Email"
          name="email"
          rules={[{ required: true, message: "Please input your email!" }]}
          style={{ width: "40%" }}
        >
          <Input type='email' onChange={e => setEmail(e.target.value)}/>
        </Form.Item>

        <Form.Item
          label="Password"
          name="password"
          rules={[{ required: true, message: "Please input your password!" }]}
          style={{ width: "40%" }}
        >
          <Input.Password onChange={e => setPassword(e.target.value)}/>
        </Form.Item>

        {/* <Form.Item
          label="Confirm Password"
          name="confirm password"
          rules={[{ required: true, message: "Please input your password!" }]}
          style={{ width: "40%" }}
        >
          <Input.Password onChange={e => setConfirmPassword(e.target.value)}/>
        </Form.Item> */}

        <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
          <Button type="primary" htmlType="submit" onClick={onSubmit}>
            Submit
          </Button>
        </Form.Item>
      </Form>

      <Footer />
    </>
  );
}

export default register;
